feat: ✨ added pages template
js-tasks-ru/htmlcss-20240216_rainy-sky pull request #12
Opened 2024-03-17 19:53 UTC by rain84

2024-03-17 19:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-21 21:15 UTC, GSemikozov requested changes

2024-03-21 21:15 UTC, GSemikozov commented on pages/template.css
> +.page {
и все равно солянка из компонентов в одном файле)
page, header, footer, container - это у нас уже есть.
content + sidebar + navigation - такие же отдельные компоненты, как выше упомянутые. 
надо раскидать по папкам.
насчет грида - слишком сложный и неочевидный лэйаут, я бы советовал не усложнять.

2024-03-21 21:15 UTC, GSemikozov commented on pages/template.css
> +.footer {
да, и у слову, если надо проставлять grid-area по структуре дочерним элементам - то через микс (.page__footer)

2024-03-22 09:55 UTC, rain84 commented on pages/template.css
> +.footer {
Хорошо )

2024-07-03 04:50 UTC, closed without merging