feat: ✨ added Modal component
js-tasks-ru/htmlcss-20240216_rainy-sky pull request #14
Opened 2024-03-20 14:33 UTC by rain84

Added Modal component

2024-03-20 14:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-20 20:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-20 20:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-21 12:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-21 13:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-21 21:22 UTC, GSemikozov requested changes

2024-03-21 21:22 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +    <div class="modal__overlay">
сын является отцом своего папы?)
в общем, элемент нельзя использовать снаружи блока, которому он принадлежит, особенно - заворачивать в элемент сам блок. 
ну и сам этот элемент лишний (см коммент ниже)

2024-03-21 21:22 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +body[data-transition_open],
ни в коем случае глобальные атрибуты и сторонние элементы в файле стилей конкретного компонента не используем

2024-03-21 21:22 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__overlay {
советовал бы все от этой строки и до 33 удалить)

2024-03-21 21:22 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal {
блок растянуть на весь вьюпорт и через fixed, а также добавить фон через rgba (и тогда никакие отдельные overlay не нужны)

2024-03-21 21:22 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal {
а то что описано здесь - это уже на самом деле элемент блока, например .modal__window

2024-03-22 10:47 UTC, rain84 commented on 05-lection3/02-modal/index.html
> +    <div class="modal__overlay">
Ну да, забавно получилось )

2024-03-22 10:52 UTC, rain84 commented on 05-lection3/02-modal/modal.css
> +.modal {
По поводу блока. Тогда получится класс, аналогичный .modal__overlay
Наверное, будет проще переименовать

2024-07-03 04:50 UTC, closed without merging