feat: ✨ added Tooltip component
js-tasks-ru/htmlcss-20240216_rainy-sky pull request #15
Opened 2024-03-21 17:42 UTC by rain84

Added Tooltip component

2024-03-21 17:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-21 21:23 UTC, GSemikozov requested changes

2024-03-21 21:23 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body {
не нужно, удалим

2024-03-21 21:23 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  .tooltip__trigger:hover + &,
нам точно нужно здесь использовать вложенные селекоры?

2024-03-22 09:52 UTC, rain84 commented on 05-lection3/01-tooltip/tooltip.css
> +  .tooltip__trigger:hover + &,
Думаю, что да
В объяснении на лекции вы тоже их использовали, только под другим синтаксисом

2024-03-22 09:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-22 10:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-22 12:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-22 12:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-28 16:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-07-03 04:50 UTC, closed without merging