Feature/hometask 1
js-tasks-ru/htmlcss-20240216_rainy-sky pull request #7
Opened 2024-03-01 17:20 UTC by rain84

1. Added HomePage layout
2. Added Button component
3. Added Accordion component

2024-03-01 17:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-03 12:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-03 12:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-03 16:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-04 11:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-04 16:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-05 14:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-05 14:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-05 21:44 UTC, GSemikozov requested changes

2024-03-05 21:44 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    /* pointer-events: none; */
именно это надо, а cursor выше не нужен

2024-03-05 21:44 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  width: 579px;
лишнее ограничение

2024-03-05 21:44 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  display: inline-block;
в данном случае инлайн-блок не надо)

2024-03-05 21:44 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  padding: 24px 32px;
если open - то снизу паддинг 32

2024-03-06 12:01 UTC, rain84 commented on 03-lection1/02-accordion/accordion.css
> +  width: 579px;
Если не указать ширину, то в закрытом состоянии аккордеон скукожится по ширине текста в заголовке ("Accordion item 1"). Задам ширину в 100%, чтобы реальными размеры аккордеона определял его контейнер-родитель

2024-03-06 12:03 UTC, rain84 commented on 03-lection1/02-accordion/accordion.css
> +  display: inline-block;
Ок, спс

2024-03-06 15:40 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  width: 579px;
см коммент ниже - если это блочный элемент, то ничего не скукожится)

2024-03-06 15:42 UTC, GSemikozov requested changes

2024-03-06 15:42 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  width: 100%;
для блочного элемента это лишнее

2024-03-06 15:42 UTC, GSemikozov commented on components/preview/preview.css
> +  flex-grow: 1;
мы заранее не может знать что родитель обязательно будет флексом, где текущий блок надо будет растянуть. Это реализуется на уровне родителя через класс-микс

2024-03-06 15:42 UTC, GSemikozov commented on components/page/page.css
> +  justify-content: space-between;
лишнее

2024-03-06 15:42 UTC, GSemikozov commented on components/page/page.css
> +  text-align: center;
лишнее

2024-03-12 14:17 UTC, GSemikozov approved these changes

2024-03-12 14:17 UTC, merged